### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by lazybirdling** [a1929238/tenchi-cards-enhancer#1]
提一点小建议：v0.3.2版本强化时要求副卡必须在主卡下面，这一特性会让一些卡不能被强化，例如不能用换气扇强化瓜皮护罩，因为背包中换气扇在瓜皮护罩的上方，能否将这一特性优化？

**Comment by a1929238** [comment]
并不是在下面，而是主副卡必须处于7行内，这样才能在同一次翻页中被识别到。该项优化难度较大，且优化后会导致强化速度极大减慢，故暂时不考虑
