### ISSUE TITLE
截图

### ISSUE THREAD

**Issue by aBearKeeper** [a1929238/tenchi-cards-enhancer#2]
![B698408F8AFED4BBB60AB38513F13338](https://github.com/user-attachments/assets/4b5f5ff8-ea46-422f-a6ae-cb3ef3326745)
截图似乎不能正确截到第一行的卡片
（用的是微端

**Comment by a1929238** [comment]
这是特性，截图是通过识别第一个空行来截取剩下的完整7行的，你可以通过修改该图片和像素距离，来实现截图8行
